# Generated by Django 3.0.2 on 2020-01-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numRoom', models.CharField(max_length=3)),
                ('typeRoom', models.CharField(blank=True, choices=[('s', 'Simple'), ('d', 'Doble'), ('p', 'Premium')], default='s', help_text='Seleccione tipo de habitacion', max_length=1)),
                ('summary', models.TextField(help_text='Ingrese una descripcion de la habitacion', max_length=1000)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserva.Client')),
            ],
        ),
    ]
