# Generated by Django 3.0.2 on 2020-01-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_auto_20200117_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='client',
        ),
    ]
