# Generated by Django 3.0.2 on 2020-01-17 15:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_remove_room_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Ingrese una ID unica', primary_key=True, serialize=False)),
                ('checkIn', models.DateField(blank=True, null=True)),
                ('checkOut', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserva.Client')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserva.Room')),
            ],
        ),
    ]
