# Generated by Django 3.0.2 on 2020-01-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(help_text='Ingrese una ID unica', primary_key=True, serialize=False),
        ),
    ]
