# Generated by Django 3.0.2 on 2020-01-18 03:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_auto_20200117_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Ingrese una ID unica', primary_key=True, serialize=False),
        ),
    ]
